refresher:
  refreshInterval: 1 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
  fetchInterval: 60  # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.
